[package]
org = "tharmigan"
name = "guaranteed_delivery"
version = "0.1.0"
distribution = "2201.12.6"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "tharmigan"
name = "messaging.storeprocessor"
version = "0.1.0"
repository = "local"
